'''
Created on 2017年6月22日

@author: xiaoxi
'''

from django.conf import settings

class ConstUtil:
    QUEUE_COIN_RECORDS_INSERT='QUEUE_{}:COIN_RECORDS_INSERT'.format(settings.CUR_MAIN_COIN_CODE)
    QUEUE_COIN_PRICE_INSERT='QUEUE_{}:COIN_PRICE_INSERT'.format(settings.CUR_MAIN_COIN_CODE)
    QUEUE_COIN_DIFF_RECORDS_INSERT='QUEUE_{}:COIN_DIFF_RECORDS_INSERT'.format(settings.CUR_MAIN_COIN_CODE)
    QUEUE_BALANCE_RECORDS_INSERT='QUEUE_{}:BALANCE_RECORDS_INSERT'.format(settings.CUR_MAIN_COIN_CODE)
    QUEUE_LOG_INSERT='QUEUE_{}:LOG_INSERT'.format(settings.CUR_MAIN_COIN_CODE)
    QUEUE_USER_ORDER_INSERT='QUEUE_{}:USER_ORDER_INSERT'.format(settings.CUR_MAIN_COIN_CODE)
    QUEUE_PRICE_DIFF_NOTICE_OTHERS='QUEUE_{}:PRICE_DIFF_NOTICE_OTHERS'.format(settings.CUR_MAIN_COIN_CODE)
    QUEUE_PRICE_PROFITS_NOTICE_CLIENTS='QUEUE_{}:PRICE_PROFITS_NOTICE_CLIENTS'.format(settings.CUR_MAIN_COIN_CODE)

    #用作存储
    REDIS_STORE='REDIS_{}:STORE'.format(settings.CUR_MAIN_COIN_CODE)

    REDIS_SAVE_CUR_COINS='REDIS_{}:SAVE_CUR_COINS'.format(settings.CUR_MAIN_COIN_CODE)
    REDIS_SAVE_ONLINE_COINS_USERS= 'REDIS_{}:SAVE_ONLINE_COINS_USERS'.format(settings.CUR_MAIN_COIN_CODE)
    REDIS_SAVE_ONLINE_COIN_LIST_USERS= 'REDIS_{}:SAVE_ONLINE_COIN_LiST_USERS'.format(settings.CUR_MAIN_COIN_CODE)
    REDIS_SAVE_REAL_PRICE_DIFF= 'REDIS_{}:SAVE_REAL_PRICE_DIFF'.format(settings.CUR_MAIN_COIN_CODE)
    REDIS_SAVE_XNB_USERS_PRIVS= 'REDIS_{}:SAVE_XNB_USERS_PRIVS'.format(settings.CUR_MAIN_COIN_CODE)

    #中间币缓存key前缀
    REDIS_SITE_MAIN_CURRENCY_PRICE='REDIS_{}:SITE_MAIN_CURRENCY_PRICE'.format(settings.CUR_MAIN_COIN_CODE)

    #国际货币兑换比例key前缀
    REDIS_CURRENCY_EXCHANGE_RATE='REDIS_{}:CURRENCY_EXCHANGE_RATE'.format(settings.CUR_MAIN_COIN_CODE)

    #虚拟币兑换比例key前缀
    REDIS_XNB_EXCHANGE_RATE='REDIS_{}:XNB_EXCHANGE_RATE'.format(settings.CUR_MAIN_COIN_CODE)

    #币价重复上传key前缀
    REDIS_SITE_COIN_PRE_PRICE='REDIS_{}:SITE_COIN_PRE_PRICE'.format(settings.CUR_MAIN_COIN_CODE)


    #重复值检测key前缀
    REDIS_CHECK_DUP_KEY_VALUE='REDIS_{}:CHECK_DUP_KEY_VALUE'.format(settings.CUR_MAIN_COIN_CODE)

    #主币默认价格
    REDIS_MAIN_COIN_DEFAULT_PRICE='REDIS_{}:MAIN_COIN_DEFAULT_PRICE'.format(settings.CUR_MAIN_COIN_CODE)

    REDIS_SAVE_CUR_BALANCES='REDIS_{}:SAVE_CUR_BALANCES'.format(settings.CUR_MAIN_COIN_CODE)
    REDIS_USER_CHECK_ORDER='REDIS_{}:USER_CHECK_ORDER'.format(settings.CUR_MAIN_COIN_CODE)
    REDIS_USER_CONFIRM_ORDER='REDIS_{}:USER_CONFIRM_ORDER'.format(settings.CUR_MAIN_COIN_CODE)
    REDIS_USER_ORDER_RECORD='REDIS_{}:USER_ORDER_RECORD'.format(settings.CUR_MAIN_COIN_CODE)


    #订单锁时间
    ORDER_INSTANTS_LOCK_SECONDS=1200
    #检测确认双边可否下单超时时间
    ORDER_CHECK_TIMEOUT_SECONDS=20

    REDIS_PAUSE_SERV='REDIS_{}:PAUSE_SERV'.format(settings.CUR_MAIN_COIN_CODE)

    #某币最新价前缀
    REDIS_COIN_LASTEST_PRICE='REDIS_{}:COIN_LASTEST_PRICE'.format(settings.CUR_MAIN_COIN_CODE)

    #公共缓存key
    REDIS_COMMON_CACHE='REDIS_{}:COMMON_CACHE'.format(settings.CUR_MAIN_COIN_CODE)

    #是否推送客户端差价消息
    REDIS_PROFITS_NOTICE_CLIENTS='REDIS_{}:PROFITS_NOTICE_CLIENTS'.format(settings.CUR_MAIN_COIN_CODE)

    #是否推送客户端差价消息
    REDIS_JS_FILE_CACHE='REDIS_{}:JS_FILE_CACHE'.format(settings.CUR_MAIN_COIN_CODE)


